// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr2lGfeC5km0_VA1MSsqOYbL5JzzpZRro',
    appId: '1:922129047722:android:80c31efc037226f73f30d3',
    messagingSenderId: '922129047722',
    projectId: 'batwara-32454',
    databaseURL: 'https://batwara-32454-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'batwara-32454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD032xb8HHdIIxvQmY_LB_St0Z-6I4JPGw',
    appId: '1:922129047722:ios:9c405a73e498fad43f30d3',
    messagingSenderId: '922129047722',
    projectId: 'batwara-32454',
    databaseURL: 'https://batwara-32454-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'batwara-32454.appspot.com',
    iosBundleId: 'com.tejasbadone.budgeto',
  );
}
